Repository wilhelm-lab/spectrum_io, pull requests merged in 2024-08, with the labels that each got.

#68 Feature/documentation
  README.rst
  ReadMe.md
  docs/API.rst
  docs/_key_contributors.rst
  docs/_static/custom_cookietemple.css
  docs/_templates/autosummary/base.rst
  docs/authors.rst
  docs/code_of_conduct.rst
  docs/conf.py
  docs/contributing.rst
  docs/index.rst
  docs/installation.rst
  docs/modules.rst
  docs/news.rst
  docs/quickstart.rst
  docs/reference.rst
  docs/requirements.txt
  docs/spectrum_io.file.rst
  docs/spectrum_io.raw.rst
  docs/spectrum_io.rst
  docs/spectrum_io.search_result.rst
  docs/spectrum_io.spectral_library.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  requirements.txt
  spectrum_io/__init__.py
Labels: enhancement, chore

#137 Feature/speclib custom mods
  poetry.lock
  pyproject.toml
  requirements.txt
  spectrum_io/spectral_library/dlib.py
  spectrum_io/spectral_library/msp.py
  spectrum_io/spectral_library/spectral_library.py
  spectrum_io/spectral_library/spectronaut.py
  tests/unit_tests/test_spectral_library.py
Labels: enhancement

#141 Housekeeping
  spectrum_io/file/parquet.py
  spectrum_io/raw/msraw.py
  tests/unit_tests/test_parquet.py
Labels: enhancement

#142 fixed filtering sequences properly
  spectrum_io/search_result/search_results.py
Labels: bug

#143 Fix/filter search result columns
  .cookietemple.yml
  .github/release-drafter.yml
  cookietemple.cfg
  docs/conf.py
  pyproject.toml
  spectrum_io/__init__.py
  spectrum_io/__main__.py
  spectrum_io/search_result/maxquant.py
  spectrum_io/search_result/search_results.py
Labels: bug
